name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend
        id: build-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false  # Не пушим сразу
          tags: vs1lence/kursach:frontend  # Изменяем тег

      - name: Build Backend
        id: build-backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false  # Не пушим сразу
          tags: vs1lence/kursach:backend  # Изменяем тег

      # Сохраним образы как артефакты
      - name: Save Docker images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}}" > images.txt
        # Сохраняем список образов в файл

      # Загрузка образов
      - name: Upload Images Artifact
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: images.txt

  push:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    needs: build  # Указывает, что этот job зависит от выполнения job build

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Docker Images Artifact
        uses: actions/download-artifact@v2
        with:
          name: images

      - name: Load Docker images
        run: |
          while IFS= read -r image; do
            # Здесь выполняем push образов
            docker pull $image  # Получаем необходимый образ
            docker tag $image $image  # Это встроенный шаг, если образ был отклонен, удалить эту строку
          done < images.txt

      - name: Push Frontend
        run: |
          docker push vs1lence/kursach:frontend

      - name: Push Backend
        run: |
          docker push vs1lence/kursach:backend
