name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend
        id: build-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false  
          tags: vs1lence/kursach:frontend  

      - name: Build Backend
        id: build-backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false  
          tags: vs1lence/kursach:backend  

     
      - name: Save Docker images
        run: |
          docker save vs1lence/kursach:frontend vs1lence/kursach:backend -o images.tar

  push:
    name: Push Docker Images to Docker Hub
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load Docker images
        run: |
          docker load -i images.tar  # Загружаем артефакты

      - name: Push Frontend
        run: |
          docker push vs1lence/kursach:frontend

      - name: Push Backend
        run: |
          docker push vs1lence/kursach:backend
