name: main

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build frontend
        id: build-frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: vs1lence/kursach:latest

      - name: build backend
        id: build-backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: vs1lence/kursach:latest

  push:
    name: Push Docker images to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: vs1lence/kursach:latest

      - name: push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: vs1lence/kursach:latest
